repo_url: https://github.com/ihc_projeto
repo_name: IHC_2026.1_Grupo06

site_url: https://github.com/ihc_projeto
site_name: Book de IHC e Acessibilidade

use_directory_urls: False

# Aqui está a SUA estrutura organizada de forma simples
nav:
  - Início: 'index.md'
  - 1. Pocket IHC: '1_pocket_ihc.md'
  - 2. Guia de Acessibilidade: '2_acessibilidade.md'
  - 3. Metodologia de Avaliação: '3_metodologia.md'
  - 4. Avaliação na Prática: '4_avaliacao_pratica.md'
  - 5. Resultados: '5_resultados.md'
  - 6. Referências Bibliográficas: '6_referencias.md'

site_name: Book de IHC e Acessibilidade

# Configurações do Tema (Agora vai funcionar tudo!)
site_name: Book de IHC e Acessibilidade

site_name: Book de IHC e Acessibilidade

site_name: Book de IHC e Acessibilidade

theme:
  name: material
  language: pt-BR
  font:
    text: Plus Jakarta Sans
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.instant
  palette:
    # ☀️ MODO CLARO: Topo grafite escuro (Passa em todos os testes de contraste da WCAG)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: slate        
      accent: blue          
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # 🌙 MODO ESCURO: Todo apagado estilo VS Code
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black        
      accent: cyan          
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

# ⚠️ ATENÇÃO: Deixe essa linha ativada para o MkDocs ler o seu arquivo de letras grossas!
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  

extra_javascript:
  - https://cdn.jsdelivr.net/npm/chart.js